---
# tasks file for installdocker

# Install Docker.
#

- name: Install dependencies
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: 'apt-transport-https' }
    - { name: 'ca-certificates' }
    - { name: 'curl' }

- name: Enable keys for Docker repository
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE package
  apt:
    name: docker-ce
    update_cache: yes

# Install Docker Compose.
#

- name: Get docker-compose release list using GitHub API
  get_url:
      url: https://api.github.com/repos/docker/compose/releases/latest
      dest: /tmp/api
      force: yes
      mode: 0755

- name: Get latest version string for Docker Compose
  shell: cat /tmp/api | grep 'tag_name' | cut -d\" -f22
  register: compose_version

- name: Get docker-compose {{ compose_version.stdout}} from github.com/docker release page
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    backup: yes
    force: yes
    mode: 0755
